#!/bin/sh

cpus=("      " "CPU0   " "CPU1   " "CPU2   " "CPU3   ")
min=("Min: " -1 -1 -1 -1)
cur=("Cur: " -1 -1 -1 -1)
max=("Max: " -1 -1 -1 -1)

for CPU_num in 0 1 2 3
do
	min[CPU_num+1]=" "$(sudo cat /sys/devices/system/cpu/cpu${CPU_num}/cpufreq/cpuinfo_min_freq)
	cur[CPU_num+1]=$(sudo cat /sys/devices/system/cpu/cpu${CPU_num}/cpufreq/cpuinfo_cur_freq)
	max[CPU_num+1]=$(sudo cat /sys/devices/system/cpu/cpu${CPU_num}/cpufreq/cpuinfo_max_freq)
done

echo "${cpus[@]}"
echo "${min[@]}"
echo "${cur[@]}"
echo "${max[@]}"
